spring:
  application:
    name: dpis
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:user@example.com}
    password: ${MAIL_PASSWORD:dummypassword123}
    from: ${MAIL_FROM:mail@example.com} # Add this line
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
        debug: ${MAIL_DEBUG:true}

resilience4j:
  ratelimiter:
    enabled: ${RATE_LIMIT_ENABLED:false}
    configs:
      default:
        registerHealthIndicator: true
        limitForPeriod: ${RATE_LIMIT_DEFAULT_LIMIT:100}
        limitRefreshPeriod: ${RATE_LIMIT_DEFAULT_REFRESH:1s}
        timeoutDuration: ${RATE_LIMIT_DEFAULT_TIMEOUT:0}
        allowHealthIndicator: true
      per-client:
        registerHealthIndicator: true
        limitForPeriod: ${RATE_LIMIT_CLIENT_LIMIT:10}
        limitRefreshPeriod: ${RATE_LIMIT_CLIENT_REFRESH:1m}
        timeoutDuration: ${RATE_LIMIT_CLIENT_TIMEOUT:0}
        allowHealthIndicator: true
    instances:
      # Global limits
      auth-global:
        baseConfig: default
        limitForPeriod: ${RATE_LIMIT_AUTH_GLOBAL_LIMIT:1000}
        limitRefreshPeriod: ${RATE_LIMIT_AUTH_GLOBAL_REFRESH:1m}
      api-global:
        baseConfig: default
        limitForPeriod: ${RATE_LIMIT_API_GLOBAL_LIMIT:3000}
        limitRefreshPeriod: ${RATE_LIMIT_API_GLOBAL_REFRESH:1m}
      # Per-client limits
      auth-client:
        baseConfig: per-client
        limitForPeriod: ${RATE_LIMIT_AUTH_CLIENT_LIMIT:10}
        limitRefreshPeriod: ${RATE_LIMIT_AUTH_CLIENT_REFRESH:1m}
      api-client:
        baseConfig: per-client
        limitForPeriod: ${RATE_LIMIT_API_CLIENT_LIMIT:300}
        limitRefreshPeriod: ${RATE_LIMIT_API_CLIENT_REFRESH:1m}

app:
  admin:
    email: ${ADMIN_EMAIL:admin@likhupike.gov.np}
    password: ${ADMIN_PASSWORD:Admin@123}
  frontend-url: ${FRONTEND_URL:http://localhost:3000}

jwt:
  secret-key: ${JWT_SECRET:464CC3302A0EF7195BD26AA6948E76B7CD112C735A42B3EF11E36FD39} # Change in production
  expiration: 24 # hours
  refresh-expiration: 168 # 7 days in hours

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
    # Add additional customizations
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    path: /swagger-ui.html
