spring:
    application:
        name: dpms
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.xml