===== Data Model

The WardTimeSeriesPopulation entity implements a comprehensive data model for tracking population statistics over time at the ward level.

[plantuml]
----
@startuml
' Core models
abstract class BaseEntity
interface DataAggregatable
interface HistoryViewable
interface ExternalSystemSyncable

' Supporting Classes
class PopulationAgeDistribution {
  +UUID id
  +UUID timeSeriesId
  +Integer year
  +Map<AgeGroup, Integer> maleDistribution
  +Map<AgeGroup, Integer> femaleDistribution
  +Map<AgeGroup, Integer> thirdGenderDistribution
  +Double median age
  +Double dependencyRatio
  +Double childDependencyRatio
  +Double agedDependencyRatio
  +Double ageingIndex
  +Double potentialSupportRatio
  +String dataSource
  +Boolean isProjected
  +ConfidenceLevel confidenceLevel
  +String notes
  +LocalDateTime lastUpdated
  +UUID lastUpdatedBy
}

class BoundaryChangeAdjustment {
  +UUID id
  +UUID timeSeriesId
  +UUID oldBoundaryId
  +UUID newBoundaryId
  +LocalDate changeDate
  +BoundaryChangeType changeType
  +Map<String, Double> populationAllocationFactors
  +Double areaChangePercent
  +Double populationAffectedPercent
  +UUID changeDecreeId
  +String changeDescription
  +LocalDateTime createdAt
  +UUID createdBy
}

class PopulationProjection {
  +UUID id
  +UUID timeSeriesId
  +Integer projectionYear
  +ProjectionScenario scenario
  +Integer projectedPopulation
  +Integer projectedMalePopulation
  +Integer projectedFemalePopulation
  +Integer projectedThirdGenderPopulation
  +Integer projectedHouseholds
  +Double confidenceIntervalLower
  +Double confidenceIntervalUpper
  +ProjectionMethod method
  +String methodologyDescription
  +Set<UUID> baselineTimeSeriesIds
  +UUID modelConfigurationId
  +String assumptions
  +LocalDateTime createdAt
  +UUID createdBy
  +LocalDateTime lastUpdated
  +UUID lastUpdatedBy
}

class InterpolationModel {
  +UUID id
  +UUID timeSeriesId
  +Integer startYear
  +Integer endYear
  +InterpolationMethod method
  +Map<String, Object> modelParameters
  +Double r2Value
  +Double meanAbsoluteError
  +Boolean isValidated
  +String notes
  +UUID validatedBy
  +LocalDateTime lastUpdated
}

enum AgeGroup {
  UNDER_5
  AGE_5_9
  AGE_10_14
  AGE_15_19
  AGE_20_24
  AGE_25_29
  AGE_30_34
  AGE_35_39
  AGE_40_44
  AGE_45_49
  AGE_50_54
  AGE_55_59
  AGE_60_64
  AGE_65_69
  AGE_70_74
  AGE_75_79
  AGE_80_84
  AGE_85_PLUS
}

enum BoundaryChangeType {
  SPLIT
  MERGE
  ANNEXATION
  DETACHMENT
  REDESIGNATION
  NEW_CREATION
}

enum ProjectionScenario {
  LOW_GROWTH
  MEDIUM_GROWTH
  HIGH_GROWTH
  CONSTANT_GROWTH
  NATURAL_INCREASE_ONLY
  MIGRATION_ADJUSTED
  CUSTOM
}

enum ProjectionMethod {
  ARITHMETIC
  GEOMETRIC
  EXPONENTIAL
  COHORT_COMPONENT
  RATIO
  REGRESSION
  CUSTOM
}

enum InterpolationMethod {
  LINEAR
  CUBIC_SPLINE
  LOGISTIC
  EXPONENTIAL
  STEP_FUNCTION
}

enum ConfidenceLevel {
  HIGH
  MEDIUM
  LOW
  VERY_LOW
  UNKNOWN
}

enum TimePeriodType {
  ANNUAL
  CENSUS
  QUARTER
  MONTH
  SPECIFIC_DATE
}

' WardTimeSeriesPopulation implementation
class WardTimeSeriesPopulation {
  ' From BaseEntity
  +UUID id
  +LocalDateTime createdAt
  +UUID createdBy
  +LocalDateTime lastModifiedAt
  +UUID lastModifiedBy
  
  ' Administrative context
  +UUID demographicSummaryId
  +UUID wardId
  +String wardCode
  +String wardName
  +UUID municipalityId
  +String municipalityCode
  +String municipalityName
  +UUID districtId
  +String districtCode
  +String districtName
  +UUID provinceId
  +String provinceCode
  +String provinceName
  
  ' Time series data
  +Integer year
  +LocalDate pointInTime
  +String timePeriod
  +Boolean isProjected
  +Boolean isRevised
  +TimePeriodType periodType
  +Integer totalPopulation
  +Integer malePopulation
  +Integer femalePopulation
  +Integer thirdGenderPopulation
  +Double sexRatio
  +Integer households
  +Double averageHouseholdSize
  +Double populationDensity
  +Double annualGrowthRate
  +Double populationGrowthPercent
  
  ' Census-specific data
  +Boolean isCensusYear
  +String censusReference
  +UUID censusDataSourceId
  
  ' Methodology data
  +ProjectionMethod projectionMethod
  +EstimationTechnique estimationTechnique
  +String methodologyDescription
  +String methodologyFormula
  +UUID methodologyDocumentId
  +ConfidenceLevel confidenceLevel
  +Double marginOfError
  +String notes
  
  ' Previous reference
  +UUID previousTimeSeriesId
  +Double changeFromPrevious
  +Double changePercentFromPrevious
  
  ' Administrative context tracking
  +Boolean reflectsAdminBoundaryChange
  +UUID previousAdminBoundaryId
  +String boundaryChangeDescription
  +LocalDate boundaryChangeDate
  
  ' Relationships
  +PopulationAgeDistribution ageDistribution
  +List<BoundaryChangeAdjustment> boundaryChanges
  +List<PopulationProjection> projections
  +InterpolationModel interpolationModel
  
  ' Methods
  +Double calculateGrowthRate(Integer baseYear, Integer targetYear)
  +Integer interpolatePopulation(Integer targetYear)
  +Integer extrapolatePopulation(Integer futureYear, ExtrapolationMethod method)
  +Map<Integer, Integer> generatePopulationTrend(Integer startYear, Integer endYear)
  +Double calculatePopulationShare(UUID largerAreaId)
  +Long getPopulationChange(UUID compareToSeriesId)
  +Double getCompoundAnnualGrowthRate(UUID compareToSeriesId)
  +List<WardTimeSeriesPopulation> getTimeSeries(Integer startYear, Integer endYear)
  +WardTimeSeriesPopulation getTimeSeriesForYear(Integer year)
  +WardTimeSeriesPopulation recalculateWithNewBoundaries(UUID newBoundaryId)
  +Double calculateDemographicIndex(IndexType indexType)
}

enum EstimationTechnique {
  INTERPOLATION
  HOUSING_UNIT
  COMPONENT_CHANGE
  SAMPLE_SURVEY
  REMOTE_SENSING
  REGISTRATION_DATA
}

enum ExtrapolationMethod {
  LINEAR
  EXPONENTIAL
  LOGARITHMIC
  POLYNOMIAL
  GEOMETRIC
}

enum IndexType {
  DEPENDENCY_RATIO
  AGING_INDEX
  POTENTIAL_SUPPORT_RATIO
  URBANIZATION_RATE
}

' Inheritance relationships
BaseEntity <|-- WardTimeSeriesPopulation
BaseEntity <|-- PopulationAgeDistribution
BaseEntity <|-- BoundaryChangeAdjustment
BaseEntity <|-- PopulationProjection
BaseEntity <|-- InterpolationModel

' Interface implementation
WardTimeSeriesPopulation ..|> DataAggregatable
WardTimeSeriesPopulation ..|> HistoryViewable
WardTimeSeriesPopulation ..|> ExternalSystemSyncable

' Class relationships
WardTimeSeriesPopulation "1" -- "0..1" PopulationAgeDistribution
WardTimeSeriesPopulation "1" -- "0..many" BoundaryChangeAdjustment
WardTimeSeriesPopulation "1" -- "0..many" PopulationProjection
WardTimeSeriesPopulation "1" -- "0..1" InterpolationModel
WardTimeSeriesPopulation -- EstimationTechnique
WardTimeSeriesPopulation -- ProjectionMethod
WardTimeSeriesPopulation -- ConfidenceLevel
WardTimeSeriesPopulation -- TimePeriodType
PopulationAgeDistribution -- AgeGroup
BoundaryChangeAdjustment -- BoundaryChangeType
PopulationProjection -- ProjectionScenario
PopulationProjection -- ProjectionMethod
InterpolationModel -- InterpolationMethod
@enduml
----

The data model captures the multifaceted nature of population time series at the ward level, with special attention to Nepal's unique administrative structure and demographic contexts.

==== Core Entity: WardTimeSeriesPopulation

[cols="1,1,3", options="header"]
|===
| Attribute | Type | Description
| id | UUID | Unique identifier for the ward time series
| demographicSummaryId | UUID | Reference to the demographic summary this record belongs to
| wardId | UUID | Reference to the ward administrative area
| wardCode | String | Code for the ward (e.g., "05")
| wardName | String | Name of the ward
| municipalityId | UUID | Reference to the municipality containing the ward
| municipalityCode | String | Code for the municipality
| municipalityName | String | Name of the municipality
| districtId | UUID | Reference to the district containing the municipality
| districtCode | String | Code for the district
| districtName | String | Name of the district
| provinceId | UUID | Reference to the province containing the district
| provinceCode | String | Code for the province
| provinceName | String | Name of the province
| year | Integer | Year of the population data
| pointInTime | LocalDate | Specific point in time for the data
| timePeriod | String | Descriptive time period label
| isProjected | Boolean | Whether this data is projected rather than measured
| isRevised | Boolean | Whether this is a revised estimate
| periodType | TimePeriodType | Type of time period (ANNUAL, CENSUS, etc.)
| totalPopulation | Integer | Total population count
| malePopulation | Integer | Male population count
| femalePopulation | Integer | Female population count
| thirdGenderPopulation | Integer | Third gender population count
| sexRatio | Double | Number of males per 100 females
| households | Integer | Number of households
| averageHouseholdSize | Double | Average number of persons per household
| populationDensity | Double | Population per square kilometer
| annualGrowthRate | Double | Annual population growth rate
| populationGrowthPercent | Double | Percentage change in population
| isCensusYear | Boolean | Whether this is census year data
| censusReference | String | Reference to the census
| censusDataSourceId | UUID | Reference to census data source
| projectionMethod | ProjectionMethod | Method used for projection if projected
| estimationTechnique | EstimationTechnique | Technique used for estimation if estimated
| methodologyDescription | String | Description of methodology used
| methodologyFormula | String | Formula used in estimation/projection
| methodologyDocumentId | UUID | Reference to detailed methodology document
| confidenceLevel | ConfidenceLevel | Confidence level of the data
| marginOfError | Double | Statistical margin of error
| notes | String | Additional notes about the data
| previousTimeSeriesId | UUID | Reference to previous time point
| changeFromPrevious | Double | Absolute change from previous time point
| changePercentFromPrevious | Double | Percentage change from previous time point
| reflectsAdminBoundaryChange | Boolean | Whether this reflects an administrative boundary change
| previousAdminBoundaryId | UUID | Reference to previous boundary definition
| boundaryChangeDescription | String | Description of boundary changes
| boundaryChangeDate | LocalDate | Date of boundary change
|===

==== Supporting Entity: PopulationAgeDistribution

Provides age-specific population breakdown for demographic analysis.

[cols="1,1,3", options="header"]
|===
| Attribute | Type | Description
| id | UUID | Unique identifier
| timeSeriesId | UUID | Reference to parent time series
| year | Integer | Year of the distribution
| maleDistribution | Map | Distribution of male population by age group
| femaleDistribution | Map | Distribution of female population by age group
| thirdGenderDistribution | Map | Distribution of third gender population by age group
| medianAge | Double | Median age of the population
| dependencyRatio | Double | Ratio of dependents to working-age population
| childDependencyRatio | Double | Ratio of children to working-age population
| agedDependencyRatio | Double | Ratio of elderly to working-age population
| ageingIndex | Double | Ratio of elderly to children
| potentialSupportRatio | Double | Ratio of working-age to elderly population
| dataSource | String | Source of the age distribution data
| isProjected | Boolean | Whether this distribution is projected
| confidenceLevel | ConfidenceLevel | Confidence level of the data
| notes | String | Additional notes
| lastUpdated | LocalDateTime | When the distribution was last updated
| lastUpdatedBy | UUID | Who last updated the distribution
|===

==== Supporting Entity: BoundaryChangeAdjustment

Records administrative boundary changes affecting population time series.

[cols="1,1,3", options="header"]
|===
| Attribute | Type | Description
| id | UUID | Unique identifier
| timeSeriesId | UUID | Reference to parent time series
| oldBoundaryId | UUID | Reference to old boundary definition
| newBoundaryId | UUID | Reference to new boundary definition
| changeDate | LocalDate | When the boundary change occurred
| changeType | BoundaryChangeType | Type of boundary change
| populationAllocationFactors | Map | Factors for allocating population across boundary changes
| areaChangePercent | Double | Percentage change in physical area
| populationAffectedPercent | Double | Percentage of population affected
| changeDecreeId | UUID | Reference to legal decree for change
| changeDescription | String | Detailed description of boundary change
| createdAt | LocalDateTime | When this record was created
| createdBy | UUID | Who created this record
|===

==== Supporting Entity: PopulationProjection

Stores population projections for future years.

[cols="1,1,3", options="header"]
|===
| Attribute | Type | Description
| id | UUID | Unique identifier
| timeSeriesId | UUID | Reference to parent time series
| projectionYear | Integer | Year being projected
| scenario | ProjectionScenario | Scenario type (high/medium/low growth, etc.)
| projectedPopulation | Integer | Projected total population
| projectedMalePopulation | Integer | Projected male population
| projectedFemalePopulation | Integer | Projected female population
| projectedThirdGenderPopulation | Integer | Projected third gender population
| projectedHouseholds | Integer | Projected number of households
| confidenceIntervalLower | Double | Lower bound of confidence interval
| confidenceIntervalUpper | Double | Upper bound of confidence interval
| method | ProjectionMethod | Method used for projection
| methodologyDescription | String | Description of methodology
| baselineTimeSeriesIds | Set | References to baseline data points
| modelConfigurationId | UUID | Reference to model configuration
| assumptions | String | Documented assumptions for projection
| createdAt | LocalDateTime | When projection was created
| createdBy | UUID | Who created the projection
| lastUpdated | LocalDateTime | When last updated
| lastUpdatedBy | UUID | Who last updated the projection
|===

==== Supporting Entity: InterpolationModel

Stores information about interpolation models used for intercensal estimates.

[cols="1,1,3", options="header"]
|===
| Attribute | Type | Description
| id | UUID | Unique identifier
| timeSeriesId | UUID | Reference to parent time series
| startYear | Integer | Start year for interpolation
| endYear | Integer | End year for interpolation
| method | InterpolationMethod | Method used for interpolation
| modelParameters | Map | Parameters defining the model
| r2Value | Double | R-squared value for model fit
| meanAbsoluteError | Double | Mean absolute error of model
| isValidated | Boolean | Whether model has been validated
| notes | String | Additional notes about the model
| validatedBy | UUID | Who validated the model
| lastUpdated | LocalDateTime | When model was last updated
|===

==== Enumerations

===== TimePeriodType
Categorizes the type of time period represented.

* `ANNUAL`: Standard yearly data
* `CENSUS`: Official census data point
* `QUARTER`: Quarterly data point
* `MONTH`: Monthly data point
* `SPECIFIC_DATE`: Data for a specific date

===== ProjectionMethod
Methods used for population projection.

* `ARITHMETIC`: Simple linear projection
* `GEOMETRIC`: Constant percentage growth rate
* `EXPONENTIAL`: Continuous compounding growth
* `COHORT_COMPONENT`: Age-structured projection
* `RATIO`: Based on ratio to another area
* `REGRESSION`: Statistical regression model
* `CUSTOM`: Custom methodology

===== EstimationTechnique
Techniques used for population estimation.

* `INTERPOLATION`: Mathematical interpolation between known points
* `HOUSING_UNIT`: Based on housing unit counts
* `COMPONENT_CHANGE`: Based on births, deaths, migration
* `SAMPLE_SURVEY`: Based on sample surveys
* `REMOTE_SENSING`: Based on satellite imagery analysis
* `REGISTRATION_DATA`: Based on administrative registrations

===== ConfidenceLevel
Indicates the level of confidence in the data.

* `HIGH`: High confidence (typically census data)
* `MEDIUM`: Medium confidence
* `LOW`: Low confidence
* `VERY_LOW`: Very low confidence
* `UNKNOWN`: Confidence level cannot be determined

===== BoundaryChangeType
Types of administrative boundary changes.

* `SPLIT`: Division of one unit into multiple units
* `MERGE`: Combination of multiple units into one
* `ANNEXATION`: Addition of area from another unit
* `DETACHMENT`: Removal of area to another unit
* `REDESIGNATION`: Change in designation without boundary change
* `NEW_CREATION`: Creation of a new administrative unit

===== ProjectionScenario
Scenarios for population projections.

* `LOW_GROWTH`: Conservative growth scenario
* `MEDIUM_GROWTH`: Moderate growth scenario
* `HIGH_GROWTH`: Aggressive growth scenario
* `CONSTANT_GROWTH`: Unchanging growth rate
* `NATURAL_INCREASE_ONLY`: Based only on births/deaths
* `MIGRATION_ADJUSTED`: Includes migration patterns
* `CUSTOM`: Custom scenario

===== InterpolationMethod
Methods used for interpolating between known data points.

* `LINEAR`: Simple linear interpolation
* `CUBIC_SPLINE`: Smooth curve fitting
* `LOGISTIC`: S-curve interpolation
* `EXPONENTIAL`: Exponential growth model
* `STEP_FUNCTION`: Discrete step changes

===== IndexType
Demographic indices that can be calculated.

* `DEPENDENCY_RATIO`: Ratio of dependents to working-age
* `AGING_INDEX`: Ratio of elderly to children
* `POTENTIAL_SUPPORT_RATIO`: Working-age to elderly ratio
* `URBANIZATION_RATE`: Rate of urban population growth

==== Database Schema Implementation

The WardTimeSeriesPopulation entity and its related entities are mapped to the following database schema:

```sql
-- Main ward time series population table
CREATE TABLE ward_time_series_population (
  id UUID PRIMARY KEY,
  demographic_summary_id UUID NOT NULL REFERENCES demographic_summary(id),
  
  -- Administrative context
  ward_id UUID NOT NULL REFERENCES administrative_area(id),
  ward_code VARCHAR(20) NOT NULL,
  ward_name VARCHAR(100) NOT NULL,
  municipality_id UUID NOT NULL REFERENCES administrative_area(id),
  municipality_code VARCHAR(20) NOT NULL,
  municipality_name VARCHAR(100) NOT NULL,
  district_id UUID NOT NULL REFERENCES administrative_area(id),
  district_code VARCHAR(20) NOT NULL,
  district_name VARCHAR(100) NOT NULL,
  province_id UUID NOT NULL REFERENCES administrative_area(id),
  province_code VARCHAR(20) NOT NULL,
  province_name VARCHAR(100) NOT NULL,
  
  -- Time series data
  year INT NOT NULL,
  point_in_time DATE,
  time_period VARCHAR(50),
  is_projected BOOLEAN DEFAULT FALSE,
  is_revised BOOLEAN DEFAULT FALSE,
  period_type VARCHAR(20),
  
  -- Population data
  total_population INT NOT NULL,
  male_population INT,
  female_population INT,
  third_gender_population INT,
  sex_ratio NUMERIC(10,2),
  households INT,
  average_household_size NUMERIC(10,2),
  population_density NUMERIC(10,2),
  annual_growth_rate NUMERIC(10,4),
  population_growth_percent NUMERIC(10,2),
  
  -- Census-specific data
  is_census_year BOOLEAN DEFAULT FALSE,
  census_reference VARCHAR(50),
  census_data_source_id UUID,
  
  -- Methodology data
  projection_method VARCHAR(30),
  estimation_technique VARCHAR(30),
  methodology_description TEXT,
  methodology_formula TEXT,
  methodology_document_id UUID,
  confidence_level VARCHAR(20),
  margin_of_error NUMERIC(10,2),
  notes TEXT,
  
  -- Previous reference
  previous_time_series_id UUID,
  change_from_previous NUMERIC(10,2),
  change_percent_from_previous NUMERIC(10,2),
  
  -- Administrative context tracking
  reflects_admin_boundary_change BOOLEAN DEFAULT FALSE,
  previous_admin_boundary_id UUID,
  boundary_change_description TEXT,
  boundary_change_date DATE,
  
  -- Audit fields
  created_at TIMESTAMP NOT NULL,
  created_by UUID NOT NULL,
  last_modified_at TIMESTAMP NOT NULL,
  last_modified_by UUID NOT NULL,
  
  -- Constraints
  CONSTRAINT fk_demographic_summary FOREIGN KEY (demographic_summary_id) REFERENCES demographic_summary(id),
  CONSTRAINT fk_ward FOREIGN KEY (ward_id) REFERENCES administrative_area(id),
  CONSTRAINT fk_municipality FOREIGN KEY (municipality_id) REFERENCES administrative_area(id),
  CONSTRAINT fk_district FOREIGN KEY (district_id) REFERENCES administrative_area(id),
  CONSTRAINT fk_province FOREIGN KEY (province_id) REFERENCES administrative_area(id),
  CONSTRAINT fk_previous_time_series FOREIGN KEY (previous_time_series_id) REFERENCES ward_time_series_population(id),
  CONSTRAINT fk_methodology_document FOREIGN KEY (methodology_document_id) REFERENCES document(id),
  CONSTRAINT uk_ward_year UNIQUE (ward_id, year)
);

-- Population age distribution
CREATE TABLE population_age_distribution (
  id UUID PRIMARY KEY,
  time_series_id UUID NOT NULL REFERENCES ward_time_series_population(id),
  year INT NOT NULL,
  median_age NUMERIC(5,2),
  dependency_ratio NUMERIC(10,2),
  child_dependency_ratio NUMERIC(10,2),
  aged_dependency_ratio NUMERIC(10,2),
  ageing_index NUMERIC(10,2),
  potential_support_ratio NUMERIC(10,2),
  data_source VARCHAR(255),
  is_projected BOOLEAN DEFAULT FALSE,
  confidence_level VARCHAR(20),
  notes TEXT,
  last_updated TIMESTAMP,
  last_updated_by UUID,
  CONSTRAINT fk_time_series FOREIGN KEY (time_series_id) REFERENCES ward_time_series_population(id)
);

-- Age distribution details by age group
CREATE TABLE population_by_age_group (
  distribution_id UUID NOT NULL REFERENCES population_age_distribution(id),
  age_group VARCHAR(20) NOT NULL,
  male_count INT,
  female_count INT,
  third_gender_count INT,
  PRIMARY KEY (distribution_id, age_group),
  CONSTRAINT fk_distribution FOREIGN KEY (distribution_id) REFERENCES population_age_distribution(id)
);

-- Boundary change adjustments
CREATE TABLE boundary_change_adjustment (
  id UUID PRIMARY KEY,
  time_series_id UUID NOT NULL REFERENCES ward_time_series_population(id),
  old_boundary_id UUID,
  new_boundary_id UUID,
  change_date DATE NOT NULL,
  change_type VARCHAR(20) NOT NULL,
  area_change_percent NUMERIC(10,2),
  population_affected_percent NUMERIC(10,2),
  change_decree_id UUID,
  change_description TEXT,
  created_at TIMESTAMP NOT NULL,
  created_by UUID NOT NULL,
  CONSTRAINT fk_time_series FOREIGN KEY (time_series_id) REFERENCES ward_time_series_population(id)
);

-- Population allocation factors for boundary changes
CREATE TABLE population_allocation_factor (
  adjustment_id UUID NOT NULL REFERENCES boundary_change_adjustment(id),
  factor_key VARCHAR(50) NOT NULL,
  factor_value NUMERIC(10,4) NOT NULL,
  PRIMARY KEY (adjustment_id, factor_key),
  CONSTRAINT fk_adjustment FOREIGN KEY (adjustment_id) REFERENCES boundary_change_adjustment(id)
);

-- Population projections
CREATE TABLE population_projection (
  id UUID PRIMARY KEY,
  time_series_id UUID NOT NULL REFERENCES ward_time_series_population(id),
  projection_year INT NOT NULL,
  scenario VARCHAR(30) NOT NULL,
  projected_population INT NOT NULL,
  projected_male_population INT,
  projected_female_population INT,
  projected_third_gender_population INT,
  projected_households INT,
  confidence_interval_lower NUMERIC(10,2),
  confidence_interval_upper NUMERIC(10,2),
  method VARCHAR(30) NOT NULL,
  methodology_description TEXT,
  model_configuration_id UUID,
  assumptions TEXT,
  created_at TIMESTAMP NOT NULL,
  created_by UUID NOT NULL,
  last_updated TIMESTAMP,
  last_updated_by UUID,
  CONSTRAINT fk_time_series FOREIGN KEY (time_series_id) REFERENCES ward_time_series_population(id),
  CONSTRAINT uk_projection UNIQUE (time_series_id, projection_year, scenario)
);

-- Baseline time series for projections
CREATE TABLE projection_baseline (
  projection_id UUID NOT NULL REFERENCES population_projection(id),
  baseline_time_series_id UUID NOT NULL REFERENCES ward_time_series_population(id),
  PRIMARY KEY (projection_id, baseline_time_series_id),
  CONSTRAINT fk_projection FOREIGN KEY (projection_id) REFERENCES population_projection(id),
  CONSTRAINT fk_baseline_time_series FOREIGN KEY (baseline_time_series_id) REFERENCES ward_time_series_population(id)
);

-- Interpolation models
CREATE TABLE interpolation_model (
  id UUID PRIMARY KEY,
  time_series_id UUID NOT NULL REFERENCES ward_time_series_population(id),
  start_year INT NOT NULL,
  end_year INT NOT NULL,
  method VARCHAR(30) NOT NULL,
  r2_value NUMERIC(10,4),
  mean_absolute_error NUMERIC(10,4),
  is_validated BOOLEAN DEFAULT FALSE,
  notes TEXT,
  validated_by UUID,
  last_updated TIMESTAMP,
  CONSTRAINT fk_time_series FOREIGN KEY (time_series_id) REFERENCES ward_time_series_population(id)
);

-- Interpolation model parameters
CREATE TABLE interpolation_model_parameter (
  model_id UUID NOT NULL REFERENCES interpolation_model(id),
  parameter_key VARCHAR(50) NOT NULL,
  parameter_value VARCHAR(255) NOT NULL,
  PRIMARY KEY (model_id, parameter_key),
  CONSTRAINT fk_model FOREIGN KEY (model_id) REFERENCES interpolation_model(id)
);

-- Indexes for performance
CREATE INDEX idx_wtsp_ward_year ON ward_time_series_population(ward_id, year);
CREATE INDEX idx_wtsp_municipality ON ward_time_series_population(municipality_id);
CREATE INDEX idx_wtsp_district ON ward_time_series_population(district_id);
CREATE INDEX idx_wtsp_province ON ward_time_series_population(province_id);
CREATE INDEX idx_wtsp_year ON ward_time_series_population(year);
CREATE INDEX idx_wtsp_is_census ON ward_time_series_population(is_census_year);
CREATE INDEX idx_projection_year ON population_projection(projection_year);
CREATE INDEX idx_boundary_change ON boundary_change_adjustment(change_date);
```

This database schema efficiently organizes the complex data required for ward-level population time series analysis while maintaining the relationships between entities. The use of proper foreign keys ensures referential integrity, while strategic indexes support the performance requirements of time series queries and administrative hierarchy aggregations.
